name: Azure Deployment

on:
  push:
    branches:
      - master 

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    env:
      ACR_REGISTRY: ajaxclusterappacr.azurecr.io
      BACKEND_IMAGE_NAME: backend
      FRONTEND_IMAGE_NAME: frontend
      BACKEND_APP_NAME: backend-app
      FRONTEND_APP_NAME: frontend-app

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Login to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: ${{ env.ACR_REGISTRY }}
        username: ${{ env.ACR_REGISTRY }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Build and push backend Docker image
      working-directory: backend
      run: |
        docker build . -t ${{ env.ACR_REGISTRY }}/${{ env.BACKEND_IMAGE_NAME }}:${{ github.sha }}
        docker push ${{ env.ACR_REGISTRY }}/${{ env.BACKEND_IMAGE_NAME }}:${{ github.sha }}

    - name: Build and push frontend Docker image
      working-directory: frontend
      run: |
        docker build . -t ${{ env.ACR_REGISTRY }}/${{ env.FRONTEND_IMAGE_NAME }}:${{ github.sha }}
        docker push ${{ env.ACR_REGISTRY }}/${{ env.FRONTEND_IMAGE_NAME }}:${{ github.sha }}

    - name: Deploy to Azure Web App - Backend
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.BACKEND_APP_NAME }}
        images: ${{ env.ACR_REGISTRY }}/${{ env.BACKEND_IMAGE_NAME }}:${{ github.sha }}

    - name: Deploy to Azure Web App - Frontend
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.FRONTEND_APP_NAME }}
        images: ${{ env.ACR_REGISTRY }}/${{ env.FRONTEND_IMAGE_NAME }}:${{ github.sha }}
